GamesBundle\Entity\Developer:
    type: entity
    repositoryClass: GamesBundle\Entity\DeveloperRepository
    table: developer
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
            nullable: false
        country:
            type: string
            lenght: 50
        description:
            type: text
            nullable: true
        logo:
            type: string
            length: 100
        created:
            type: datetime