GamesBundle\Entity\Game:
    type: entity
    repositoryClass: GamesBundle\Entity\GameRepository
    table: game
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
            nullable: false
        description:
            type: text
            nullable: true
        year:
            type: integer
            nullable: false
        cover:
            type: string
            length: 100
    manyToOne:
        developer:
            targetEntity: Developer
            joinColumn:
                name: developer_id
                referencedColumnName: id

